import { GoogleAuth } from "google-auth-library";

// Place in /api/chat.js (Node.js)
export default async function handler(req, res) {
    // Allow CORS
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");

    if (req.method === "OPTIONS") {
        res.status(200).end(); // Handle preflight
        return;
    }
    
    if (req.method !== "POST") {
        return res.status(405).json({ error: "Method not allowed" });
    }
    
    const userMessage = req.body?.message;
    if (!userMessage) {
        return res.status(200).json({ reply: "[DEBUG API ERROR] Missing user message in request." });
    }

    const projectId = process.env.PROJECT_ID;
    const dataStoreId = process.env.DATA_STORE_ID;
    const credentialsString = process.env.GOOGLE_CREDENTIALS;

    if (!projectId || !dataStoreId || !credentialsString) {
        return res.status(200).json({ reply: "[DEBUG API ERROR] Missing Google Cloud configuration (PROJECT_ID, DATA_STORE_ID, GOOGLE_CREDENTIALS) in environment variables." });
    }

    try {
        let credentials;
        try {
            credentials = JSON.parse(credentialsString);
        } catch (e) {
            return res.status(200).json({ reply: `[DEBUG API ERROR] Invalid GOOGLE_CREDENTIALS JSON format: ${e.message}` });
        }

        const auth = new GoogleAuth({
            credentials,
            scopes: ['https://www.googleapis.com/auth/cloud-platform']
        });
        
        const client = await auth.getClient();
        const accessToken = await client.getAccessToken();

        const location = 'us-central1'; // Vertex AI models default location
        const model = 'gemini-1.5-flash';
        const url = `https://${location}-aiplatform.googleapis.com/v1/projects/${projectId}/locations/${location}/publishers/google/models/${model}:generateContent`;

        const response = await fetch(url, {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${accessToken.token}`,
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                contents: [
                    {
                        role: "user",
                        parts: [{ text: userMessage }]
                    }
                ],
                systemInstruction: {
                    parts: [{ text: "You are a friendly e-commerce assistant named Lily who helps customers find fashion and jewelry products." }]
                },
                tools: [
                    {
                        retrieval: {
                            vertexAiSearch: {
                                datastore: `projects/${projectId}/locations/global/collections/default_collection/dataStores/${dataStoreId}`
                            }
                        }
                    }
                ]
            }),
        });

        const data = await response.json();
    
        if (!response.ok) {
            return res.status(200).json({ reply: `[DEBUG API ERROR] Vertex AI responded with: ${JSON.stringify(data)}` });
        }
        
        const reply = data.candidates?.[0]?.content?.parts?.[0]?.text || "[DEBUG API ERROR] No reply generated by Vertex AI";
    
        res.status(200).json({ reply });
    } catch (err) {
        console.error("Error communicating with Vertex AI:", err);
        res.status(200).json({ reply: `[DEBUG JS ERROR] ${err.message}` });
    }
}