import { ConversationalSearchServiceClient } from '@google-cloud/discoveryengine';

// Place in /api/chat.js (Node.js)
export default async function handler(req, res) {
    // Allow CORS
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");

    // Handle preflight
    if (req.method === "OPTIONS") {
        return res.status(200).end();
    }
    
    // Check method
    if (req.method !== "POST") {
        return res.status(405).json({ reply: "[DEBUG API ERROR] Method not allowed. Must be POST." });
    }

    try {
        // 1. Get user message
        const userMessage = req.body?.message;
        if (!userMessage) {
            return res.status(200).json({ reply: "[DEBUG API ERROR] Missing user message. Verify 'message' in your JSON payload." });
        }

        // 2. Validate env vars
        const projectId = process.env.PROJECT_ID;
        const dataStoreId = process.env.DATA_STORE_ID;
        const credentialsString = process.env.GOOGLE_CREDENTIALS;

        if (!projectId || !dataStoreId || !credentialsString) {
            return res.status(200).json({ reply: "[DEBUG API ERROR] Missing Google Cloud config (PROJECT_ID, DATA_STORE_ID, GOOGLE_CREDENTIALS)" });
        }

        let credentials;
        try {
            credentials = JSON.parse(credentialsString);
        } catch (e) {
            return res.status(200).json({ reply: `[DEBUG API ERROR] Invalid GOOGLE_CREDENTIALS JSON format: ${e.message}` });
        }

        // 3. Initialize the official SDK Client
        const client = new ConversationalSearchServiceClient({
            credentials
        });

        // 4. Build the correct 'Serving Config' path directly to your Engine (App) rules
        // Since you are using an App Engine that wraps multiple datastores, we use the Engine path builder here.
        // We will keep passing your DATA_STORE_ID Vercel variable, because you placed the Engine ID inside it.
        const servingConfig = client.projectLocationCollectionEngineServingConfigPath(
            projectId,
            'global',
            'default_collection',
            dataStoreId, // This is your App/Engine ID (lily-knowledge-base_1775128374137)
            'default_search'
        );

        // 5. Query Discovery Engine (Agent Builder)
        const request = {
            servingConfig: servingConfig,
            query: { text: userMessage },
            // Optional: Related questions settings can be added here if needed
        };

        const [response] = await client.answerQuery(request);

        // 6. Extract the clean text summary provided natively by the engine
        const answerText = response.answer?.answerText || "[DEBUG API ERROR] No answer text was generated by the datastore app.";

        // 7. Send back our perfectly formatted JSON response
        return res.status(200).json({ reply: answerText });

    } catch (err) {
        console.error("Agent Builder SDK Error:", err);
        // Output exactly what went wrong for your Flutter app temporarily:
        return res.status(200).json({ reply: `[DEBUG SDK ERROR] ${err.message}` });
    }
}